/* eslint-disable camelcase */
import type { Metadata } from 'next'
import { Roboto, Contrail_One } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

const contrailOne = Contrail_One({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-contrail-one',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className="antialiased">
      <head>
        <title>Lucas Farias das Neves</title>
      </head>
      <body className={`${roboto.variable} ${contrailOne.variable}`}>
        <div className="flex min-h-screen flex-col justify-start bg-neutral-900 ">
          <Header />
          <main className="relative  mx-auto w-full max-w-[76rem]">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}

// No arquivo layout é adicionado todo o conteudo que serão renderizados em todas as páginas do site.
